### ISSUE TITLE
Feature: FastAPI call-compatible replacement

### ISSUE THREAD

**Issue by rswgnu** [unum-cloud/ujrpc#74]
### Describe what you are looking for

I am a bit confused by your comparison to FastAPI.  FastAPI can rapidly build REST APIs atop relational databases, with a flexible middleware component for customizing responses.  Does your system do anything like this?  Why compare the two if you can't quickly replace FastAPI with your system, i.e. you would have to rewrite a great deal of code.  If you can replace it, please explain a bit.

From the existing README, it seems like you are focused only on lower-level protocol replacement for increased speed using JSON-RPC but then the comparison between the systems doesn't make much sense to me.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Contact Details

rswgnu@github.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hey, @rswgnu!

Yes, you are right. FastAPI focuses on REST over HTTP and TCP, while UCall implements JSON-RPC and can work with and without the HTTP layer. The reason we compare them is due to similar functionality and primary interface. Both use Python decorators to define RPC endpoints.

The performance wins in UCall come from something other than choosing JSON-RPC over REST. They come from Linux kernel bypass tricks and reduced memory allocations. Those numbers would still hold for the REST implementation, which is being added by @ishkhan42 as I type this 😄 

The release is scheduled for August and will also bring out-of-the-box TLS support, which will make it easier than ever to build High-Performance web servers for micro-deployments, like AWS Lambdas, where putting an NGINX in front of your microservice can be too much of a hassle... and added latency. So stay tuned 🤗

**Comment by rswgnu** [comment]
Sounds good.  Look forward to it.  Your whole ecosystem sounds quite exciting.  Keep at it. On Aug 1, 2023, at 2:41 AM, Ash Vardanian ***@***.***> wrote:﻿
Hey, @rswgnu!
Yes, you are right. FastAPI focuses on REST over HTTP and TCP, while UCall implements JSON-RPC and can work with and without the HTTP layer. The reason we compare them is due to similar functionality and primary interface. Both use Python decorators to define RPC endpoints.
The performance wins in UCall come from something other than choosing JSON-RPC over REST. They come from Linux kernel bypass tricks and reduced memory allocations. Those numbers would still hold for the REST implementation, which is being added by @ishkhan42 as I type this 😄
The release is scheduled for August and will also bring out-of-the-box TLS support, which will make it easier than ever to build High-Performance web servers for micro-deployments, like AWS Lambdas, where putting an NGINX in front of your microservice can be too much of a hassle... and added latency. So stay tuned 🤗
